
server.port=8081


weather.api.key=...
weather.api.base-url=...
weather.api.units=metric



spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


logging.level.com.weather=DEBUG
